import {
  User,
  NeedItem,
  OfferItem,
  MatchResult,
  OpportunityItem,
  LeadItem,
  ConversationItem,
  ChatMessage,
  PartnerItem,
  AnalyticsSummary,
  CommunityItem,
  CommunityPostItem,
  EventItem,
  MarketplaceListingItem,
  RewardItem,
  WalletSummary,
  ReferralInfo,
  MembershipInfo,
  PlanItem,
  CallSession,
  LiveRoomItem,
  ProfessionalContentItem,
  CreatorAnalytics,
  OrganizationItem,
  OrganizationMemberItem,
  TeamItem,
  EnterpriseAnalytics,
  ReportItem,
  TrustScoreReport,
  PrivacySettings,
  AuditLogItem,
  AdminPlatformMetrics,
  FeatureFlags,
} from '../types';

export const CURRENT_USER: User = {
  id: 'usr_curr_01',
  email: 'alex.morgan@nexastech.com',
  phoneNumber: '+91 98765 43210',
  role: 'BUSINESS',
  isPhoneVerified: true,
  isEmailVerified: true,
  needsOnboarding: false,
  createdAt: '2026-01-15T10:00:00Z',
  profile: {
    id: 'prof_01',
    userId: 'usr_curr_01',
    firstName: 'Alex',
    lastName: 'Morgan',
    fullName: 'Alex Morgan',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    headline: 'Founder & Head of Tech @ Nexas Digital',
    bio: 'Building enterprise mobile & cloud architectures. Passionate about B2B growth and partnership ecosystems.',
    city: 'Bangalore',
    country: 'India',
    skills: ['Mobile Development', 'React Native', 'NestJS', 'Cloud Architecture', 'Product Strategy'],
    interests: ['AI Automation', 'B2B Networking', 'SaaS Growth', 'Angel Investing'],
    profileCompletionPercentage: 95,
  },
  business: {
    id: 'biz_01',
    ownerUserId: 'usr_curr_01',
    businessName: 'Nexas Digital Solutions',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150',
    categoryId: 'cat_it_soft',
    categoryName: 'IT & Software Development',
    description: 'Premier digital product studio specializing in high-performance cross-platform apps, microservices backend, and UI/UX design.',
    websiteUrl: 'https://nexasdigital.io',
    city: 'Bangalore',
    country: 'India',
    isVerified: true,
    employeeCountRange: '11-50 employees',
    services: ['Mobile App Development', 'Full-Stack Web Dev', 'Cloud DevOps', 'UI/UX Design Systems'],
    products: ['Nexas Cloud Sync SDK', 'Lip Talk Component Suite'],
  },
};

export const INITIAL_NEEDS: NeedItem[] = [
  {
    id: 'need_01',
    ownerType: 'BUSINESS',
    ownerId: 'biz_01',
    ownerName: 'Nexas Digital Solutions',
    ownerRole: 'BUSINESS',
    categoryId: 'cat_marketing',
    categoryName: 'Digital Marketing & Growth',
    title: 'Performance Marketing & Lead Gen Agency',
    description: 'Looking for a verified digital marketing partner to run B2B LinkedIn & Google search campaigns for our SaaS clients.',
    tags: ['B2B Marketing', 'Google Ads', 'LinkedIn Campaigns', 'Lead Generation'],
    priority: 'HIGH',
    city: 'Bangalore',
    budgetMin: 50000,
    budgetMax: 120000,
    currency: 'INR/mo',
    status: 'ACTIVE',
    createdAt: '2026-08-10T12:00:00Z',
  },
  {
    id: 'need_02',
    ownerType: 'BUSINESS',
    ownerId: 'biz_01',
    ownerName: 'Nexas Digital Solutions',
    ownerRole: 'BUSINESS',
    categoryId: 'cat_legal',
    categoryName: 'Legal & Compliance',
    title: 'Corporate Legal Advisor for Tech Contracts',
    description: 'Need legal consultation for enterprise MSA contracts, IP protection, and client master service agreements.',
    tags: ['Corporate Law', 'Tech Contracts', 'IP Protection', 'Compliance'],
    priority: 'MEDIUM',
    city: 'Bangalore',
    budgetMin: 30000,
    budgetMax: 70000,
    currency: 'INR',
    status: 'ACTIVE',
    createdAt: '2026-08-14T09:30:00Z',
  },
];

export const INITIAL_OFFERS: OfferItem[] = [
  {
    id: 'off_01',
    ownerType: 'BUSINESS',
    ownerId: 'biz_01',
    ownerName: 'Nexas Digital Solutions',
    ownerRole: 'BUSINESS',
    categoryId: 'cat_it_soft',
    categoryName: 'IT & Software Development',
    title: 'Custom Mobile & Web Application Engineering',
    description: 'End-to-end production development with React Native, TypeScript, NestJS, and scalable cloud deployment.',
    tags: ['React Native', 'TypeScript', 'NestJS', 'Mobile Apps', 'PostgreSQL'],
    pricingModel: 'FIXED',
    city: 'Bangalore',
    status: 'ACTIVE',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'off_02',
    ownerType: 'BUSINESS',
    ownerId: 'biz_01',
    ownerName: 'Nexas Digital Solutions',
    ownerRole: 'BUSINESS',
    categoryId: 'cat_design',
    categoryName: 'UI/UX & Product Design',
    title: 'High-Converting B2B UI/UX Design & Prototyping',
    description: 'Complete Figma design systems, user flows, interactive prototypes, and design-to-code handover.',
    tags: ['UI/UX Design', 'Figma', 'Design Systems', 'Mobile UI'],
    pricingModel: 'HOURLY',
    city: 'Bangalore',
    status: 'ACTIVE',
    createdAt: '2026-08-05T14:15:00Z',
  },
];

export const MATCHES_DATA: MatchResult[] = [
  {
    id: 'match_01',
    targetId: 'biz_growth_pulse',
    targetType: 'BUSINESS',
    targetName: 'GrowthPulse Media',
    targetAvatar: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150',
    targetHeadline: 'B2B Performance Marketing & Lead Acquisition Agency',
    targetCity: 'Bangalore',
    targetRole: 'BUSINESS',
    matchedNeedTitle: 'Performance Marketing & Lead Gen Agency',
    matchedOfferTitle: 'B2B Growth & Multi-Channel Lead Campaigns',
    matchScore: 94,
    matchScorePercent: '94%',
    primaryReason: 'Offers exact high-priority service you need (B2B Lead Gen)',
    reasons: [
      { factor: 'Category Match', description: 'Exact match in Digital Marketing & Growth', scoreContribution: 40 },
      { factor: 'Tags & Skills', description: 'Matched tags: B2B Marketing, Google Ads, Lead Generation', scoreContribution: 24 },
      { factor: 'Location Proximity', description: 'Both located in Bangalore (within 8 km)', scoreContribution: 15 },
      { factor: 'Verified Activity', description: 'Verified business profile active 2 hours ago', scoreContribution: 10 },
      { factor: 'Reciprocal Need', description: 'They are actively seeking React Native App Dev (which you offer)', scoreContribution: 5 },
    ],
    isReciprocal: true,
    reciprocalDetail: 'GrowthPulse Media needs "Mobile App Development" which matches your offer!',
  },
  {
    id: 'match_02',
    targetId: 'biz_lex_tech',
    targetType: 'BUSINESS',
    targetName: 'LexTech Advisors LLP',
    targetAvatar: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=150',
    targetHeadline: 'Technology Law, Startup IP & SaaS Contracts',
    targetCity: 'Bangalore',
    targetRole: 'BUSINESS',
    matchedNeedTitle: 'Corporate Legal Advisor for Tech Contracts',
    matchedOfferTitle: 'Tech MSA & IP Protection Retainers',
    matchScore: 89,
    matchScorePercent: '89%',
    primaryReason: 'Specialized corporate legal practice matching your compliance need',
    reasons: [
      { factor: 'Category Match', description: 'Exact match in Legal & Compliance', scoreContribution: 40 },
      { factor: 'Tags & Skills', description: 'Matched tags: Corporate Law, Tech Contracts, IP Protection', scoreContribution: 22 },
      { factor: 'Location Proximity', description: 'Located in Bangalore', scoreContribution: 15 },
      { factor: 'Profile Strength', description: '100% verified legal partner', scoreContribution: 12 },
    ],
    isReciprocal: false,
  },
  {
    id: 'match_03',
    targetId: 'usr_rohit_sharma',
    targetType: 'USER',
    targetName: 'Rohit Sharma',
    targetAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    targetHeadline: 'Senior Growth Strategist & Paid Ads Consultant',
    targetCity: 'Bangalore',
    targetRole: 'INDIVIDUAL',
    matchedNeedTitle: 'Performance Marketing & Lead Gen Agency',
    matchedOfferTitle: 'Performance Ads & Meta/Google Funnels',
    matchScore: 86,
    matchScorePercent: '86%',
    primaryReason: 'Individual consultant with proven ROI track record in B2B ads',
    reasons: [
      { factor: 'Category Match', description: 'Match in Digital Marketing', scoreContribution: 38 },
      { factor: 'Tags & Skills', description: 'Overlap in Google Ads, Lead Generation', scoreContribution: 20 },
      { factor: 'Geographic Vicinity', description: 'Bangalore (Indiranagar)', scoreContribution: 15 },
      { factor: 'Activity Score', description: 'Top rated provider with 12 completed opportunities', scoreContribution: 13 },
    ],
    isReciprocal: false,
  },
];

export const OPPORTUNITIES_DATA: OpportunityItem[] = [
  {
    id: 'opp_01',
    creatorId: 'usr_vikram_singh',
    creatorName: 'Vikram Singh',
    creatorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    creatorRole: 'BUSINESS',
    businessId: 'biz_finflow',
    businessName: 'FinFlow Logistics Tech',
    categoryId: 'cat_it_soft',
    categoryName: 'IT & Software Development',
    title: 'Looking for React Native Dev Team to build B2B Delivery App',
    description: 'We are seeking an experienced mobile development agency to build our driver dispatch and proof-of-delivery cross-platform app. Must have real-time GPS tracking and offline sync capabilities.',
    tags: ['React Native', 'TypeScript', 'Offline Sync', 'GPS Tracking', 'Mobile App'],
    budgetAmount: 350000,
    currency: 'INR',
    deadline: '2026-09-30',
    city: 'Bangalore',
    status: 'OPEN',
    interestsCount: 8,
    hasExpressedInterest: false,
    matchScore: 96,
    createdAt: '2026-08-16T11:00:00Z',
  },
  {
    id: 'opp_02',
    creatorId: 'usr_priya_nair',
    creatorName: 'Priya Nair',
    creatorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    creatorRole: 'BUSINESS',
    businessId: 'biz_health_first',
    businessName: 'HealthFirst Telemed',
    categoryId: 'cat_design',
    categoryName: 'UI/UX & Product Design',
    title: 'Senior UI/UX Designer for Patient Health Dashboard',
    description: 'Complete redesign of our patient consultation mobile app and clinic scheduling web portal. Seeking high-fidelity Figma components and user testing experience.',
    tags: ['UI/UX Design', 'Figma', 'Healthcare', 'Design Systems'],
    budgetAmount: 180000,
    currency: 'INR',
    deadline: '2026-09-15',
    city: 'Mumbai (Remote OK)',
    status: 'OPEN',
    interestsCount: 5,
    hasExpressedInterest: true,
    matchScore: 91,
    createdAt: '2026-08-15T16:45:00Z',
  },
  {
    id: 'opp_03',
    creatorId: 'usr_ananya_roy',
    creatorName: 'Ananya Roy',
    creatorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    creatorRole: 'INDIVIDUAL',
    categoryId: 'cat_marketing',
    categoryName: 'Digital Marketing & Growth',
    title: 'Seeking B2B Content Writer & SEO Specialist',
    description: 'Need long-form technical blogs and whitepapers for AI fintech product launch over the next 3 months.',
    tags: ['Content Marketing', 'SEO', 'Technical Writing', 'Fintech'],
    budgetAmount: 60000,
    currency: 'INR/mo',
    deadline: '2026-09-01',
    city: 'Remote',
    status: 'IN_DISCUSSION',
    interestsCount: 14,
    hasExpressedInterest: false,
    matchScore: 78,
    createdAt: '2026-08-12T09:15:00Z',
  },
];

export const LEADS_DATA: LeadItem[] = [
  {
    id: 'lead_01',
    businessId: 'biz_01',
    contactUserId: 'usr_vikram_singh',
    contactName: 'Vikram Singh (FinFlow)',
    contactAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    contactHeadline: 'Founder @ FinFlow Logistics Tech',
    contactCity: 'Bangalore',
    opportunityId: 'opp_01',
    opportunityTitle: 'React Native B2B Delivery App',
    title: 'FinFlow Driver Dispatch App Project',
    source: 'OPPORTUNITY',
    status: 'QUALIFIED',
    estimatedValue: 350000,
    currency: 'INR',
    notesCount: 4,
    lastContactedAt: '2026-08-18T14:30:00Z',
    createdAt: '2026-08-16T12:00:00Z',
    updatedAt: '2026-08-18T14:30:00Z',
  },
  {
    id: 'lead_02',
    businessId: 'biz_01',
    contactUserId: 'usr_growthpulse_founder',
    contactName: 'Kavita Menon (GrowthPulse)',
    contactAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    contactHeadline: 'Managing Director @ GrowthPulse Media',
    contactCity: 'Bangalore',
    title: 'Reciprocal Growth & Client App Build Partnership',
    source: 'MATCH',
    status: 'IN_DISCUSSION',
    estimatedValue: 200000,
    currency: 'INR',
    notesCount: 2,
    lastContactedAt: '2026-08-17T17:00:00Z',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-17T17:00:00Z',
  },
  {
    id: 'lead_03',
    businessId: 'biz_01',
    contactUserId: 'usr_priya_nair',
    contactName: 'Priya Nair (HealthFirst)',
    contactAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    contactHeadline: 'VP Product @ HealthFirst Telemed',
    contactCity: 'Mumbai',
    opportunityId: 'opp_02',
    opportunityTitle: 'Patient Health Dashboard UI/UX',
    title: 'Telemedicine Dashboard Redesign Contract',
    source: 'OPPORTUNITY',
    status: 'CONVERTED',
    estimatedValue: 180000,
    currency: 'INR',
    notesCount: 6,
    lastContactedAt: '2026-08-18T10:15:00Z',
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-18T10:15:00Z',
  },
];

export const CONVERSATIONS_DATA: ConversationItem[] = [
  {
    id: 'conv_01',
    contextType: 'OPPORTUNITY',
    contextId: 'opp_01',
    contextTitle: 'Opportunity: React Native B2B Delivery App',
    otherParticipant: {
      id: 'usr_vikram_singh',
      name: 'Vikram Singh',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      role: 'BUSINESS',
      isOnline: true,
    },
    lastMessage: {
      text: 'Thanks Alex! We reviewed your team portfolio for offline sync and would like to schedule a technical discovery call tomorrow at 3 PM.',
      senderId: 'usr_vikram_singh',
      createdAt: '2026-08-18T14:30:00Z',
      isRead: false,
    },
    unreadCount: 1,
    updatedAt: '2026-08-18T14:30:00Z',
  },
  {
    id: 'conv_02',
    contextType: 'NEED_OFFER_MATCH',
    contextId: 'match_01',
    contextTitle: 'Match (94%): B2B Lead Gen & Web App Development',
    otherParticipant: {
      id: 'usr_growthpulse_founder',
      name: 'Kavita Menon',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
      role: 'BUSINESS',
      isOnline: false,
    },
    lastMessage: {
      text: 'Our team is ready with the LinkedIn campaign pitch deck for Nexas. Shared the draft over email.',
      senderId: 'usr_growthpulse_founder',
      createdAt: '2026-08-17T17:00:00Z',
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: '2026-08-17T17:00:00Z',
  },
];

export const CHAT_MESSAGES_DATA: Record<string, ChatMessage[]> = {
  conv_01: [
    {
      id: 'msg_01',
      conversationId: 'conv_01',
      senderId: 'usr_curr_01',
      senderName: 'Alex Morgan',
      text: 'Hi Vikram, saw your requirement for the B2B Delivery App. At Nexas, we have built 4 production logistics apps with background GPS and SQLite offline caching.',
      isRead: true,
      createdAt: '2026-08-16T14:00:00Z',
    },
    {
      id: 'msg_02',
      conversationId: 'conv_01',
      senderId: 'usr_vikram_singh',
      senderName: 'Vikram Singh',
      text: 'Hi Alex! That matches our exact tech stack need. Do you support Android background location policies and low-power battery optimization?',
      isRead: true,
      createdAt: '2026-08-16T14:15:00Z',
    },
    {
      id: 'msg_03',
      conversationId: 'conv_01',
      senderId: 'usr_curr_01',
      senderName: 'Alex Morgan',
      text: 'Yes, we use native foreground services with batched geofence alerts to ensure compliance and sub-2% battery drain per 8h shift.',
      isRead: true,
      createdAt: '2026-08-16T14:22:00Z',
    },
    {
      id: 'msg_04',
      conversationId: 'conv_01',
      senderId: 'usr_vikram_singh',
      senderName: 'Vikram Singh',
      text: 'Thanks Alex! We reviewed your team portfolio for offline sync and would like to schedule a technical discovery call tomorrow at 3 PM.',
      isRead: false,
      createdAt: '2026-08-18T14:30:00Z',
    },
  ],
};

export const PARTNERS_DATA: PartnerItem[] = [
  {
    id: 'ptn_01',
    name: 'Rapido Enterprise Logistics',
    logoUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=150',
    categoryName: 'Intra-City Logistics & Fleet',
    description: 'On-demand corporate parcel and express delivery fleet for local businesses and retail stores.',
    coverageArea: 'Pan-India (40+ Cities)',
    websiteUrl: 'https://rapido.bike',
    exclusiveBadge: 'Eco Partner',
    offers: [
      {
        id: 'poff_01',
        partnerId: 'ptn_01',
        partnerName: 'Rapido Enterprise',
        title: '30% Off First 100 Business Deliveries',
        description: 'Exclusive B2B introductory credit for Lip Talk verified businesses.',
        discountCode: 'LIPTALK30',
        discountValue: '30% OFF',
        validUntil: '2026-12-31',
        ctaUrl: 'https://rapido.bike/business',
      },
    ],
  },
  {
    id: 'ptn_02',
    name: 'Blinkit Commerce For Work',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=150',
    categoryName: 'Instant Office Supplies & Pantry',
    description: '10-minute office pantry restocking, printer supplies, and team event essentials.',
    coverageArea: 'Metro Tier-1 & Tier-2',
    websiteUrl: 'https://blinkit.com',
    exclusiveBadge: 'Priority Supply',
    offers: [
      {
        id: 'poff_02',
        partnerId: 'ptn_02',
        partnerName: 'Blinkit Commerce',
        title: '₹2,500 Monthly Office Pantry Credits',
        description: 'Complimentary restocking credits on quarterly enterprise agreements.',
        discountCode: 'LIPBIZ2500',
        discountValue: '₹2,500 Credits',
        validUntil: '2026-11-30',
        ctaUrl: 'https://blinkit.com/b2b',
      },
    ],
  },
  {
    id: 'ptn_03',
    name: 'RedBus Corporate Commute',
    logoUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=150',
    categoryName: 'Corporate Travel & Shuttles',
    description: 'Dedicated business employee commute passes and chartered inter-city buses for corporate retreats.',
    coverageArea: 'Nationwide',
    websiteUrl: 'https://redbus.in',
    offers: [
      {
        id: 'poff_03',
        partnerId: 'ptn_03',
        partnerName: 'RedBus Corporate',
        title: '15% Cashback on Executive Shuttle Passes',
        description: 'Available for team bookings above 10 members.',
        discountCode: 'LIPTRAVEL15',
        discountValue: '15% Cashback',
        validUntil: '2026-10-31',
        ctaUrl: 'https://redbus.in/corporate',
      },
    ],
  },
];

export const ANALYTICS_DATA: AnalyticsSummary = {
  profileViews: 482,
  totalConnections: 64,
  activeMatches: 19,
  opportunitiesPosted: 3,
  leadsTotal: 12,
  leadsConverted: 4,
  conversionRatePercent: 33.3,
  pipelineValue: 730000,
};

export const COMMUNITIES_DATA: CommunityItem[] = [
  {
    id: 'comm_01',
    name: 'Bangalore Tech Founders & CTOs',
    slug: 'bangalore-tech-founders',
    description: 'Exclusive hub for technology executives, full-stack builders, and SaaS architects in Bangalore.',
    category: 'IT & Software Development',
    coverImageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600',
    avatarUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=150',
    visibility: 'PUBLIC',
    memberCount: 428,
    postCount: 34,
    isVerified: true,
    isJoined: true,
    userRole: 'OWNER',
    recommendedReason: 'Direct match for your React Native & NestJS tech stack',
    synergyScore: 98,
    rules: [
      'Share real technical insights and architectures.',
      'Post high-budget business opportunities and hiring demands.',
      'Maintain a collaborative and helpful professional environment.',
    ],
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'comm_02',
    name: 'B2B Growth & Lead Gen Guild',
    slug: 'b2b-growth-marketing',
    description: 'Performance marketers, LinkedIn outbound specialists, and acquisition strategists sharing proven playbooks.',
    category: 'Digital Marketing & Growth',
    coverImageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600',
    avatarUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150',
    visibility: 'PUBLIC',
    memberCount: 312,
    postCount: 22,
    isVerified: true,
    isJoined: false,
    recommendedReason: 'Matches your active high-priority Need in B2B Performance Marketing',
    synergyScore: 94,
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'comm_03',
    name: 'Product Design & UI/UX Architects',
    slug: 'product-design-architects',
    description: 'Figma token masters, design system specialists, and UX researchers discussing interaction design and mobile patterns.',
    category: 'UI/UX & Product Design',
    coverImageUrl: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    visibility: 'PUBLIC',
    memberCount: 265,
    postCount: 18,
    isVerified: true,
    isJoined: false,
    recommendedReason: 'Synergy with your verified UI/UX Design services',
    synergyScore: 89,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'comm_04',
    name: 'SaaS Legal & Corporate Compliance Hub',
    slug: 'saas-legal-compliance',
    description: 'Corporate retainers, cross-border MSA contracts, and DPDP compliance advisors for Indian startups.',
    category: 'Legal & Corporate Compliance',
    coverImageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600',
    avatarUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=150',
    visibility: 'PUBLIC',
    memberCount: 184,
    postCount: 14,
    isVerified: true,
    isJoined: false,
    recommendedReason: 'High enterprise relevance for contract negotiations',
    synergyScore: 84,
    createdAt: '2026-02-10T10:00:00Z',
  },
];

export const COMMUNITY_POSTS_DATA: CommunityPostItem[] = [
  {
    id: 'post_01',
    type: 'ANNOUNCEMENT',
    title: 'Best practices for React Native offline-first SQLite sync',
    content: 'We recently transitioned our client architecture from standard REST caching to SQLite local tables with background sync workers. Reduced network payload by 65% and app start latency to 120ms. Anyone else experimenting with WatermelonDB or native TurboModules?',
    likesCount: 19,
    commentsCount: 6,
    isPinned: true,
    hasLiked: true,
    userReaction: 'LIKE',
    createdAt: '2026-08-22T14:30:00Z',
    author: {
      id: 'usr_curr_01',
      role: 'BUSINESS',
      profile: {
        fullName: 'Alex Morgan',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
        headline: 'Founder & Head of Tech @ Nexas Digital',
      },
      businesses: [
        {
          businessName: 'Nexas Digital Solutions',
          logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150',
        },
      ],
    },
  },
  {
    id: 'post_02',
    type: 'QUESTION',
    title: 'Which cloud provider offers the lowest latency for Indian Redis clusters?',
    content: 'Evaluating AWS Mumbai vs GCP Delhi for low-latency WebSocket presence clustering. Looking for sub-15ms roundtrip latency during peak B2B matching spikes. Suggestions welcome!',
    likesCount: 12,
    commentsCount: 4,
    isPinned: false,
    hasLiked: false,
    createdAt: '2026-08-21T18:00:00Z',
    author: {
      id: 'usr_vikram_01',
      role: 'BUSINESS',
      profile: {
        fullName: 'Vikram Singh',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
        headline: 'CTO @ FinFlow Logistics Tech',
      },
    },
  },
];

export const EVENTS_DATA: EventItem[] = [
  {
    id: 'event_01',
    title: 'Bangalore B2B Tech & Growth Mixer 2026',
    description: 'Interactive in-person networking mixer connecting 50+ vetted software agency founders and growth directors. 3 lightning architecture teardowns followed by synergy matching sessions.',
    category: 'Networking',
    eventDate: '2026-09-18',
    startTime: '06:30 PM',
    endTime: '09:00 PM',
    locationType: 'IN_PERSON',
    locationUrlOrAddress: 'WeWork Galaxy, Residency Road, Bangalore',
    coverImageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=600',
    capacity: 75,
    registeredCount: 38,
    status: 'UPCOMING',
    isRegistered: true,
    community: {
      id: 'comm_01',
      name: 'Bangalore Tech Founders & CTOs',
      avatarUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=150',
    },
    organizer: {
      id: 'usr_curr_01',
      role: 'BUSINESS',
      profile: {
        fullName: 'Alex Morgan',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      },
    },
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'event_02',
    title: 'Mastering Outbound B2B Lead Gen & Account-Based Growth',
    description: 'Live interactive masterclass on high-converting cold email sequences, LinkedIn automation safeguards, and conversion attribution models for agency founders.',
    category: 'Workshop',
    eventDate: '2026-09-24',
    startTime: '05:00 PM',
    endTime: '07:00 PM',
    locationType: 'ONLINE',
    locationUrlOrAddress: 'https://meet.google.com/liptalk-growth-masterclass',
    coverImageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600',
    capacity: 200,
    registeredCount: 94,
    status: 'UPCOMING',
    isRegistered: false,
    community: {
      id: 'comm_02',
      name: 'B2B Growth & Lead Gen Guild',
      avatarUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150',
    },
    organizer: {
      id: 'usr_kavita_01',
      role: 'BUSINESS',
      profile: {
        fullName: 'Kavita Menon',
        avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
      },
    },
    createdAt: '2026-08-18T10:00:00Z',
  },
];

export const MARKETPLACE_LISTINGS_DATA: MarketplaceListingItem[] = [
  {
    id: 'list_01',
    title: 'Custom React Native & Cloud App Engineering',
    slug: 'custom-mobile-app-engineering',
    description: 'End-to-end mobile architecture with offline SQLite synchronization, high-frequency WebSockets, and production NestJS backend deployment.',
    category: 'IT & Software Development',
    pricingType: 'FIXED',
    price: 250000,
    currency: 'INR',
    location: 'Bangalore (Hybrid)',
    tags: ['React Native', 'TypeScript', 'NestJS', 'Offline Sync'],
    imageUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600'],
    status: 'PUBLISHED',
    promotionType: 'FEATURED',
    averageRating: 4.9,
    reviewsCount: 14,
    requestsCount: 28,
    isSaved: false,
    recommendedReason: 'Top-tier verified engineering agency in Bangalore',
    synergyScore: 98,
    createdAt: '2026-02-01T10:00:00Z',
    provider: {
      id: 'usr_curr_01',
      role: 'BUSINESS',
      profile: {
        id: 'prof_01',
        userId: 'usr_curr_01',
        firstName: 'Alex',
        lastName: 'Morgan',
        fullName: 'Alex Morgan',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
        headline: 'Founder & Head of Tech @ Nexas Digital',
        bio: 'Building enterprise mobile & cloud architectures.',
        city: 'Bangalore',
        country: 'India',
        skills: ['Mobile Development', 'React Native', 'NestJS'],
        interests: ['AI Automation', 'B2B Networking'],
        profileCompletionPercentage: 95,
      },
      businesses: [
        {
          id: 'biz_01',
          ownerUserId: 'usr_curr_01',
          businessName: 'Nexas Digital Solutions',
          logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150',
          categoryName: 'IT & Software Development',
          description: 'Premier digital product studio.',
          city: 'Bangalore',
          country: 'India',
          isVerified: true,
          services: ['Mobile App Development'],
          products: ['Nexas Cloud Sync SDK'],
        },
      ],
    },
  },
  {
    id: 'list_02',
    title: 'Enterprise Figma Design System & UX Audit',
    slug: 'enterprise-figma-design-system',
    description: 'Scalable multi-brand tokenized Figma library with WCAG 2.1 compliance and native component parity documentation.',
    category: 'UI/UX & Product Design',
    pricingType: 'HOURLY',
    price: 3500,
    currency: 'INR',
    location: 'Remote',
    tags: ['Figma Tokens', 'UX Research', 'Design Systems'],
    imageUrls: ['https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600'],
    status: 'PUBLISHED',
    promotionType: 'NORMAL',
    averageRating: 5.0,
    reviewsCount: 8,
    requestsCount: 15,
    isSaved: true,
    recommendedReason: 'Direct match for your product design needs',
    synergyScore: 92,
    createdAt: '2026-02-10T10:00:00Z',
    provider: {
      id: 'usr_sarah_01',
      role: 'BUSINESS',
      profile: {
        id: 'prof_02',
        userId: 'usr_sarah_01',
        firstName: 'Sarah',
        lastName: 'Jenkins',
        fullName: 'Sarah Jenkins',
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
        headline: 'Design Director @ Studio Craft',
        bio: 'Design systems lead.',
        city: 'Mumbai',
        country: 'India',
        skills: ['UI/UX', 'Figma'],
        interests: ['Design Systems'],
        profileCompletionPercentage: 90,
      },
    },
  },
  {
    id: 'list_03',
    title: 'B2B Account-Based Marketing & LinkedIn Outbound',
    slug: 'b2b-abm-linkedin-outbound',
    description: 'High-converting multi-touch outbound pipeline generating 20+ qualified enterprise sales calls per month.',
    category: 'Digital Marketing & Growth',
    pricingType: 'NEGOTIABLE',
    price: 75000,
    currency: 'INR',
    location: 'Bangalore',
    tags: ['B2B Lead Gen', 'ABM', 'LinkedIn Outbound'],
    imageUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600'],
    status: 'PUBLISHED',
    promotionType: 'PROMOTED',
    averageRating: 4.8,
    reviewsCount: 19,
    requestsCount: 42,
    isSaved: false,
    recommendedReason: 'Directly solves your active high-priority marketing demand',
    synergyScore: 96,
    createdAt: '2026-02-15T10:00:00Z',
    provider: {
      id: 'usr_kavita_01',
      role: 'BUSINESS',
      profile: {
        id: 'prof_03',
        userId: 'usr_kavita_01',
        firstName: 'Kavita',
        lastName: 'Menon',
        fullName: 'Kavita Menon',
        avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
        headline: 'Founder @ GrowthPulse Media',
        bio: 'B2B Growth Lead.',
        city: 'Bangalore',
        country: 'India',
        skills: ['Growth Marketing', 'Lead Gen'],
        interests: ['SaaS Growth'],
        profileCompletionPercentage: 95,
      },
    },
  },
];

export const REWARDS_DATA: RewardItem[] = [
  {
    id: 'rew_01',
    title: '₹1,500 Rapido Business Fleet Voucher',
    description: 'Redeemable for team corporate commute passes across all tier-1 cities.',
    pointsCost: 750,
    category: 'Corporate Travel',
    discountValue: '₹1,500 OFF',
    promoCodeTemplate: 'RAPIDO-BIZ',
    bannerUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=600',
    isActive: true,
  },
  {
    id: 'rew_02',
    title: '₹2,500 Blinkit Office Pantry Credit',
    description: 'Instant office replenishment credits on orders above ₹3,000.',
    pointsCost: 1200,
    category: 'Office & Supplies',
    discountValue: '₹2,500 Credits',
    promoCodeTemplate: 'BLINKIT-BIZ',
    bannerUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600',
    isActive: true,
  },
  {
    id: 'rew_03',
    title: 'LipTalk Executive Pro (1-Month Pass)',
    description: 'Unlock 2x priority matching algorithm and promoted business demands for 30 days.',
    pointsCost: 2000,
    category: 'Platform Perks',
    discountValue: '100% Free Month',
    promoCodeTemplate: 'LIPPRO-30D',
    bannerUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600',
    isActive: true,
  },
];

export const WALLET_SUMMARY_DATA: WalletSummary = {
  currentBalance: 1850,
  totalEarned: 1850,
  totalRedeemed: 0,
  transactionCount: 3,
  recentTransactions: [
    {
      id: 'tx_01',
      amount: 1000,
      type: 'EARNED',
      action: 'PROFILE_COMPLETED',
      description: 'Completed 95% Verified Business & Founder Profile',
      createdAt: '2d ago',
    },
    {
      id: 'tx_02',
      amount: 500,
      type: 'EARNED',
      action: 'REFERRAL_SUCCESS',
      description: 'Referred Vikram Singh (FinFlow Logistics Tech)',
      createdAt: '3d ago',
    },
    {
      id: 'tx_03',
      amount: 350,
      type: 'EARNED',
      action: 'COLLABORATION_COMPLETED',
      description: 'Completed B2B Synergy Deal with GrowthPulse Media',
      createdAt: '5d ago',
    },
  ],
};

export const REFERRAL_INFO_DATA: ReferralInfo = {
  referralCode: 'LIP-ALEX99',
  referralLink: 'https://liptalk.app/join?ref=LIP-ALEX99',
  rewardPerReferral: 500,
  totalReferrals: 3,
  qualifiedReferrals: 1,
  totalPointsFromReferrals: 500,
};

export const MEMBERSHIP_INFO_DATA: MembershipInfo = {
  tier: 'PRO',
  status: 'ACTIVE',
  expiresAt: '2026-12-31T23:59:59Z',
  entitlements: {
    canCreateCommunity: true,
    canCreateListing: true,
    canPromoteListing: false,
    canViewAdvancedAnalytics: true,
    maxActiveDemands: 15,
    featuredBadge: false,
    directLeadExport: false,
  },
};

export const PLANS_DATA: PlanItem[] = [
  {
    id: 'tier_free',
    name: 'Starter Networker',
    tier: 'FREE',
    pricePerMonth: 0,
    currency: 'INR',
    badge: 'Free Forever',
    features: [
      'Full Synergy Matching Engine',
      'Post up to 5 Business Demands',
      'Join Unlimited Ecosystem Guilds',
      'Contextual 1:1 Inquiries & Chat',
      'Basic CRM Lead Pipeline',
    ],
  },
  {
    id: 'tier_pro',
    name: 'Executive Pro',
    tier: 'PRO',
    pricePerMonth: 1499,
    currency: 'INR',
    badge: 'Current Plan',
    features: [
      'Everything in Starter',
      'Post up to 15 Business Demands',
      'Priority Matching Algorithm (2x Boost)',
      'Advanced Deal Conversion Analytics',
      'Create & Host Verified Guilds',
      'Custom Service Listing Badges',
    ],
  },
  {
    id: 'tier_business',
    name: 'Enterprise Scale',
    tier: 'BUSINESS',
    pricePerMonth: 4999,
    currency: 'INR',
    badge: 'Scale Tier',
    features: [
      'Everything in Executive Pro',
      'Post up to 50 Demands & Contracts',
      'Promoted Marketplace Listings (Featured)',
      'Full CRM Lead Export to CSV/ERP',
      'Dedicated Relationship Advisor',
      'Exclusive Corporate Partner Perks',
    ],
  },
];

// ==========================================
// PHASE 6: REAL-TIME & LIVE ECOSYSTEM MOCKS
// ==========================================

export const CALL_HISTORY_DATA: CallSession[] = [
  {
    id: 'call_01',
    caller: CURRENT_USER,
    receiver: {
      id: 'usr_vikram_01',
      email: 'vikram@finflow.io',
      role: 'BUSINESS',
      isPhoneVerified: true,
      isEmailVerified: true,
      needsOnboarding: false,
      createdAt: '2026-01-10T10:00:00Z',
      profile: {
        id: 'prof_vikram',
        userId: 'usr_vikram_01',
        firstName: 'Vikram',
        lastName: 'Singh',
        fullName: 'Vikram Singh',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
        headline: 'Founder & CEO @ FinFlow Logistics Tech',
        city: 'Bangalore',
        country: 'India',
        bio: 'Scaling logistics SaaS across India.',
        skills: ['Architecture', 'Scaling'],
        interests: ['Tech', 'Networking'],
        profileCompletionPercentage: 95,
      },
    },
    callType: 'VOICE',
    status: 'ENDED',
    durationSeconds: 342,
    createdAt: '2026-08-23T11:15:00Z',
  },
  {
    id: 'call_02',
    caller: {
      id: 'usr_priya_01',
      email: 'priya@zenith.design',
      role: 'INDIVIDUAL',
      isPhoneVerified: true,
      isEmailVerified: true,
      needsOnboarding: false,
      createdAt: '2026-01-12T10:00:00Z',
      profile: {
        id: 'prof_priya',
        userId: 'usr_priya_01',
        firstName: 'Priya',
        lastName: 'Sharma',
        fullName: 'Priya Sharma',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
        headline: 'Design Systems Lead @ Zenith Studio',
        city: 'Bangalore',
        country: 'India',
        bio: 'Design tokens and fintech UI/UX.',
        skills: ['Architecture', 'Scaling'],
        interests: ['Tech', 'Networking'],
        profileCompletionPercentage: 95,
      },
    },
    receiver: CURRENT_USER,
    callType: 'VIDEO',
    status: 'ENDED',
    durationSeconds: 520,
    createdAt: '2026-08-22T16:45:00Z',
  },
];

export const LIVE_ROOMS_DATA: LiveRoomItem[] = [
  {
    id: 'room_01',
    host: CURRENT_USER,
    title: 'Bangalore CTOs: Scaling High-Concurrency WebSockets & Offline Sync',
    description: 'Live interactive masterclass & architecture teardown on building real-time mobile sync with SQLite and NestJS.',
    category: 'Engineering & Architecture',
    roomType: 'WORKSHOP',
    status: 'LIVE',
    audienceCount: 38,
    coverImageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600',
    community: {
      id: 'comm_01',
      name: 'Bangalore Tech Founders & CTOs',
      slug: 'bangalore-tech-founders',
      description: 'Exclusive guild of 400+ tech founders building scalable software in India.',
      category: 'Software & Technology',
      coverImageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
      visibility: 'PUBLIC',
      memberCount: 412,
      postCount: 34,
      isVerified: true,
      isJoined: true,
      createdAt: '2026-01-15T10:00:00Z',
    },
    startedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'room_02',
    host: {
      id: 'usr_vikram_01',
      email: 'vikram@finflow.io',
      role: 'BUSINESS',
      isPhoneVerified: true,
      isEmailVerified: true,
      needsOnboarding: false,
      createdAt: '2026-01-10T10:00:00Z',
      profile: {
        id: 'prof_vikram',
        userId: 'usr_vikram_01',
        firstName: 'Vikram',
        lastName: 'Singh',
        fullName: 'Vikram Singh',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
        headline: 'Founder & CEO @ FinFlow Logistics Tech',
        city: 'Bangalore',
        country: 'India',
        bio: 'Scaling logistics SaaS across India.',
        skills: ['Architecture', 'Scaling'],
        interests: ['Tech', 'Networking'],
        profileCompletionPercentage: 95,
      },
    },
    title: 'B2B Founder Mixer: Closing Enterprise Contracts in Q4',
    description: 'Open mic networking session for SaaS founders and agency owners to share outbound strategies and active demands.',
    category: 'B2B Growth & Sales',
    roomType: 'NETWORKING',
    status: 'SCHEDULED',
    audienceCount: 14,
    coverImageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=600',
    scheduledAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const PROFESSIONAL_CONTENTS_DATA: ProfessionalContentItem[] = [
  {
    id: 'content_01',
    author: CURRENT_USER,
    contentType: 'EDUCATIONAL',
    title: 'How we architected 60fps offline synchronization in React Native',
    body: 'Deep dive into local SQLite caching, conflict-free state resolution, and binary WebSocket event streaming. Check out our verified marketplace listing for architecture retainers!',
    mediaUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600'],
    tags: ['React Native', 'Mobile Architecture', 'Offline Sync'],
    viewsCount: 480,
    likesCount: 54,
    isFollowing: true,
    createdAt: '2026-08-23T09:30:00Z',
  },
  {
    id: 'content_02',
    author: {
      id: 'usr_priya_01',
      email: 'priya@zenith.design',
      role: 'INDIVIDUAL',
      isPhoneVerified: true,
      isEmailVerified: true,
      needsOnboarding: false,
      createdAt: '2026-01-12T10:00:00Z',
      profile: {
        id: 'prof_priya',
        userId: 'usr_priya_01',
        firstName: 'Priya',
        lastName: 'Sharma',
        fullName: 'Priya Sharma',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
        headline: 'Design Systems Lead @ Zenith Studio',
        city: 'Bangalore',
        country: 'India',
        bio: 'Design tokens and fintech UI/UX.',
        skills: ['Architecture', 'Scaling'],
        interests: ['Tech', 'Networking'],
        profileCompletionPercentage: 95,
      },
    },
    contentType: 'SHOWCASE',
    title: 'Enterprise Fintech Dashboard Token System Case Study',
    body: 'How we standardized 120+ dark-mode color variables, responsive typography tokens, and high-density financial data charts for multi-tenant banking apps.',
    mediaUrls: ['https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=600'],
    tags: ['UI/UX Design', 'Design Tokens', 'Fintech UI'],
    viewsCount: 620,
    likesCount: 89,
    isFollowing: false,
    createdAt: '2026-08-22T15:00:00Z',
  },
];

export const CREATOR_ANALYTICS_DATA: CreatorAnalytics = {
  profileViews: 600,
  followersCount: 38,
  contentImpressions: 1100,
  totalLikes: 143,
  liveSessionsHosted: 3,
  totalLiveAttendees: 82,
  opportunitiesGenerated: 7,
  dealConversions: 4,
};

// ==========================================
// Phase 7 Mock Datasets
// ==========================================
export const ORGANIZATIONS_DATA: OrganizationItem[] = [
  {
    id: 'org_01',
    name: 'FinFlow Technologies Pvt Ltd',
    slug: 'finflow-technologies',
    description: 'Enterprise fintech & cross-border payments infrastructure supporting 10,000+ merchants.',
    industry: 'Financial Technology & Enterprise SaaS',
    employeeCountRange: '100-500',
    location: 'Bangalore, India',
    websiteUrl: 'https://finflow.io',
    logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150',
    verificationStatus: 'VERIFIED',
    owner: CURRENT_USER,
    maxSeats: 50,
    userRole: 'OWNER',
    isMember: true,
    createdAt: '2026-01-10T10:00:00Z',
  },
];

export const ORGANIZATION_MEMBERS_DATA: OrganizationMemberItem[] = [
  {
    id: 'mem_01',
    user: CURRENT_USER,
    role: 'OWNER',
    department: 'Executive Leadership',
    jobTitle: 'Chief Technology Officer',
    isActive: true,
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'mem_02',
    user: {
      id: 'usr_priya_01',
      email: 'priya.sharma@zenith.io',
      role: 'INDIVIDUAL',
      isPhoneVerified: true,
      isEmailVerified: true,
      needsOnboarding: false,
      createdAt: '2026-01-12T10:00:00Z',
      profile: {
        id: 'prof_priya',
        userId: 'usr_priya_01',
        firstName: 'Priya',
        lastName: 'Sharma',
        fullName: 'Priya Sharma',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
        headline: 'Head of Enterprise Sales @ FinFlow',
        city: 'Bangalore',
        country: 'India',
        bio: 'Strategic partnerships & fintech enterprise deals.',
        skills: ['Enterprise Sales', 'Negotiation'],
        interests: ['Fintech', 'SaaS'],
        profileCompletionPercentage: 95,
      },
    },
    role: 'MANAGER',
    department: 'Strategic Partnerships',
    jobTitle: 'Head of Enterprise Sales',
    isActive: true,
    createdAt: '2026-01-15T10:00:00Z',
  },
];

export const TEAMS_DATA: TeamItem[] = [
  {
    id: 'team_01',
    name: 'Core Platform & Architecture',
    department: 'ENGINEERING',
    description: 'High-throughput payment gateway and distributed ledgers.',
    membersCount: 4,
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'team_02',
    name: 'Enterprise Partnerships',
    department: 'SALES',
    description: 'Large enterprise logistics and banking deal pipeline.',
    membersCount: 3,
    createdAt: '2026-01-15T10:00:00Z',
  },
];

export const ENTERPRISE_ANALYTICS_DATA: EnterpriseAnalytics = {
  activeTeamSeats: 8,
  allocatedSeats: 50,
  totalTeams: 2,
  collaborativeDealsActive: 14,
  totalPipelineValue: '₹48,50,000',
  teamConversionRate: '68%',
  closedContractsThisQuarter: 9,
};

export const TRUST_SCORE_DATA: TrustScoreReport = {
  userId: 'usr_curr_01',
  overallScore: 92,
  maxScore: 100,
  trustTier: 'TIER_1_EXECUTIVE',
  verificationBadge: 'VERIFIED_PARTNER',
  signals: [
    {
      name: 'Identity & Contact Verification',
      score: 25,
      maxScore: 25,
      status: 'VERIFIED',
      details: 'Both phone (+91 98765 43210) and corporate email verified',
    },
    {
      name: 'Profile Completeness & Bio Clarity',
      score: 19,
      maxScore: 20,
      status: 'VERIFIED',
      details: '95% completed with verified technical skills and portfolio links',
    },
    {
      name: 'Verified Business & GST Legitimacy',
      score: 25,
      maxScore: 25,
      status: 'VERIFIED',
      details: 'Verified GSTIN: 29AAAAA0000A1Z5 • FinFlow Technologies',
    },
    {
      name: 'Peer Collaboration & Client Reviews',
      score: 18,
      maxScore: 20,
      status: 'VERIFIED',
      details: '4.9/5.0 average across 14 ecosystem contracts',
    },
    {
      name: 'Platform Standing & Age',
      score: 10,
      maxScore: 10,
      status: 'VERIFIED',
      details: 'Active member with 0 policy violations or reports',
    },
  ],
};

export const PRIVACY_SETTINGS_DATA: PrivacySettings = {
  profileVisibility: 'PUBLIC',
  searchDiscoverability: true,
  directMessaging: 'EVERYONE',
  allowCalling: 'CONNECTIONS_ONLY',
  aiRecommendationsOptIn: true,
  activityStatusVisible: true,
};

export const AUDIT_LOGS_DATA: AuditLogItem[] = [
  {
    id: 'log_01',
    action: 'ORG_CREATED',
    targetType: 'ORGANIZATION',
    targetId: 'org_01',
    description: 'Enterprise organization FinFlow Technologies workspace established',
    ipAddress: '106.51.72.18',
    createdAt: '2026-08-23T10:00:00Z',
  },
  {
    id: 'log_02',
    action: 'ROLE_ASSIGNED',
    targetType: 'USER_ROLE',
    targetId: 'usr_priya_01',
    description: 'Priya Sharma assigned MANAGER role in Enterprise Partnerships',
    ipAddress: '106.51.72.18',
    createdAt: '2026-08-23T11:15:00Z',
  },
];

export const ADMIN_METRICS_DATA: AdminPlatformMetrics = {
  dau: 1420,
  wau: 4850,
  mau: 12800,
  totalUsers: 4,
  totalOrganizations: 2,
  activeCommunities: 2,
  openOpportunities: 2,
  pendingReports: 0,
  systemStatus: 'HEALTHY',
  apiUptime: '99.98%',
  rtcSignalingUptime: '99.99%',
  avgApiLatencyMs: 42,
};

export const FEATURE_FLAGS_DATA: FeatureFlags = {
  aiAssistant: true,
  liveRooms: true,
  creatorMode: true,
  enterpriseWorkspaces: true,
  trustVerification: true,
  marketplaceMonetization: true,
  realtimeVoiceVideo: true,
};




